#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import traceback
from argparse import ArgumentParser
from enum import unique, Enum
from os import makedirs
from os.path import join, isdir, isfile
from subprocess import check_call
from xml.etree import ElementTree

from requests import Session, HTTPError


@unique
class Music(Enum):
    """NHK Gogaku music files list."""
    basic1 = 'english/basic1'
    basic2 = 'english/basic2'
    basic3 = 'english/basic3'
    kaiwa = 'english/kaiwa'
    timetrial = 'english/timetrial'
    kouryaku = 'english/kouryaku'
    business1 = 'english/business1'
    business2 = 'english/business2'
    yomu = 'english/yomu'
    enjoy = 'english/enjoy'
    chinese = 'chinese/kouza'
    chinese_stepup = 'chinese/stepup'
    hangeul = 'hangeul/kouza'
    hangeul_levelup = 'hangeul/levelup'
    italian = 'italian/kouza'
    german = 'german/kouza'
    french = 'french/kouza'
    spanish = 'spanish/kouza'
    russian = 'russian/kouza'


if __name__ == '__main__':

    # Read command options
    description = "'nhk-stream.py' downloads NHK Gogaku music files. "
    parser = ArgumentParser(description=description)
    parser.add_argument('music', type=str, nargs='+',
                        help='music file name. choose [{}]'.format(",".join([member.name for member in Music])))
    parser.add_argument('-f', '--force', action="store_true", help='overwrite files')
    parser.add_argument('-C', '--directory', type=str, default='',
                        help='change output directory (default: "%(default)s")')
    args = parser.parse_args()

    for name in args.music:
        if name not in [member.name for member in Music]:
            parser.error("Invalid sound file name [{}]".format(name))

    session = Session()

    try:
        # Gets information of the music items from XML files
        musics = dict()
        for name in args.music:
            resp = session.get("https://cgi2.nhk.or.jp/gogaku/st/xml/{}/listdataflv.xml".format(Music[name].value))
            # Checks a status code of the response
            if resp.status_code != 200:
                raise HTTPError("Invalid URL [{}]".format(resp.url), response=resp)

            root = ElementTree.fromstring(resp.content.decode())
            # Gets attributes of the music items
            musics[name] = [dict(title=e.get('title'), hdate=e.get('hdate'), kouza=e.get('kouza'), code=e.get('code'),
                                 file=e.get('file'), nendo=e.get('nendo'), pgcode=e.get('pgcode')) for e in root.iter('music')]

        # Runs a loop of proceeding the music items
        for name, data_list in musics.items():

            # Makes a directory of the music items
            dir_name = join(args.directory, name)
            if not isdir(dir_name):
                makedirs(dir_name)

            # Runs a loop of downloading the music files
            for data in data_list:
                file = join(args.directory, name, "{}_{}_{}.mp3".format(data['title'], data['nendo'], data['hdate']))
                # Checks the overwrite option
                if isfile(file) and not args.force:
                    # Skips the overwrite process
                    print('Skip Downloading {}'.format(file))
                    continue
                url = "https://nhk-vh.akamaihd.net/i/gogaku-stream/mp4/{}/master.m3u8".format(data['file'])
                # Downloads the music file with ffmpeg
                print('Download {}'.format(file))
                check_call(["ffmpeg", "-loglevel", "panic", "-nostdin", "-y", "-i", url, "-ab", "64k", "-id3v2_version", "3", file])

        exit(0)

    except Exception as e:
        print(traceback.format_exc())
        exit(1)
